### PR TITLE
Update to Elm 0.17

### PR DESCRIPTION
**Pull request by pbiggar**

### CODE REVIEW

**Comment by pbiggar** [comment]
CI failed because the package providing elm-io.sh isn't needed on elm 0.17 (see https://elm-community.github.io/elm-faq/17.html#what-is-now-in-elm-community). I don't think we need elm-io.sh anymore, so I fixed the command to not use it.

**Comment by sgraf812** [comment]
Wow, thanks!

**Comment by pbiggar** [comment]
Thank you!

If you could do a new release that would be very helpful to me. I'm currently trying to make the local version work, and that doesn't seem to be easy in elm :(

**Comment by sgraf812** [comment]
Yeah, I was working on it, but it's rather late around here and the publish doesn't seem to work as expected. Will do when I've slept, sorry.

**Comment by pbiggar** [comment]
No worries, thanks!

**Comment by sgraf812** [comment]
That should do, 1.1.2 is released.

**Pull request merged**
